services:
  mqtt-broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  tsdb:
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/tsdb-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/tsdb-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/tsdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: feira
      DOCKER_INFLUXDB_INIT_BUCKET: feira
    image: influxdb:2
    restart: always
    secrets:
      - tsdb-username
      - tsdb-password
      - tsdb-admin-token
    volumes:
      - ./tsdb/data:/var/lib/influxdb2:rw
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    depends_on:
      - tsdb
    environment:
      GF_SERVER_DOMAIN: em.sj.ifsc.edu.br
      GF_SERVER_ROOT_URL: https://em.sj.ifsc.edu.br/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: true
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
  http-proxy:
    depends_on:
      - grafana
    image: nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/em.sj.ifsc.edu.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/em.sj.ifsc.edu.br/privkey.pem:/etc/nginx/privkey.pem:ro
secrets:
  tsdb-username:
    file: secret-tsdb-username
  tsdb-password:
    file: secret-tsdb-password
  tsdb-admin-token:
    file: secret-tsdb-admin-token
